server.port=${PORT:8084}
spring.application.name=identity-service

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:none}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.servlet.multipart.max-file-size=150MB
spring.servlet.multipart.max-request-size=150MB

media.service.url=${MEDIA_SERVICE_URL:http://localhost:8082}
catalog.service.url=${CATALOG_SERVICE_URL:http://localhost:8083}

management.endpoints.web.exposure.include=health

spring.cloud.openfeign.autoconfiguration.jackson.enabled=false
spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.media.read-timeout=30000
spring.cloud.openfeign.client.config.catalog.read-timeout=10000
