server.port=${PORT:5000}
spring.application.name=majestic-food-api
spring.datasource.url=jdbc:mysql://db-mysql-nyc3-majestic-food-do-user-18688216-0.g.db.ondigitalocean.com:25060/db_majestic_food
spring.datasource.username=doadmin
spring.datasource.password=AVNS_yoN1ialwPvnRZ92Yq_6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.max-file-size=5MB
spring.jpa.show-sql=true